name: Java CI

on:
  push:
    branches: 
      - "ชาซีลอนปั่นหวานน้อยใส่ช้อกชิพ"

jobs:
  build:
    name: Build and Run Java Application
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref}}
        fetch-depth: ${{ env.PR_FETCH_DEPTH}}
        
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        
    - name: Compile Java
      run: |
        cd ชาซีลอนปั่นหวานน้อยใส่ช้อกชิพ/HolidayTravelvehicle/
        javac -d . *.java
        
    - name: Run Main Class
      run: |
        cd ชาซีลอนปั่นหวานน้อยใส่ช้อกชิพ/HolidayTravelvehicle/
        java MainClassName > output.txt

    - name: Display Output
      run: |
        cat ชาซีลอนปั่นหวานน้อยใส่ช้อกชิพ/HolidayTravelvehicle/output.txt
